### ISSUE TITLE
Cannot import

### ISSUE THREAD

**Issue by Kiffolisk** [chfoo/seedyrng#1]
I've been trying to import seedyrng into my project for a long time, but it just gives me an error like "Seedy" does not exist and stuff like that.

I know I have to import seedyrng but I can't find a way.

Yes, I installed the seedyrng haxelib and no, I'm not dumb and I know I have to import seedyrng to make it work

**Comment by chfoo** [comment]
Hi, have you gotten any other libraries to work? When you are trying to compile, do you have `-L seedyrng` (or `-lib` or `--library`) included in the haxe command?

**Comment by Kiffolisk** [comment]
I've tried using -lib, but it tells me "Error: You must have a "project.xml" file or specify another valid project file when using the 'build' command"

**Comment by chfoo** [comment]
I assumed that you are using the Haxe compiler command but it appears you are running an OpenFL/Lime project. If you are using the OpenFL/lime command, you don't use the `-L` argument but [add it in the xml as described here](https://lib.haxe.org/documentation/haxelibs-in-projects/). If you are still having trouble, can you provide the name of your OS, Haxe version, and the command that you are running?

**Comment by Kiffolisk** [comment]
Thanks, it worked!
